CREATE TABLE `t_skl` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`nomr` VARCHAR(11) NOT NULL,
	`nama` VARCHAR(100) NOT NULL,
	`tgllahir` DATE NULL DEFAULT NULL,
	`hari` VARCHAR(10) NULL DEFAULT NULL,
	`jam` VARCHAR(10) NULL DEFAULT NULL,
	`jeniskelamin` VARCHAR(1) NULL DEFAULT NULL,
	`beratbadan` VARCHAR(10) NULL DEFAULT NULL,
	`panjangbadan` VARCHAR(10) NULL DEFAULT NULL,
	`lingkarkepala` VARCHAR(10) NULL DEFAULT NULL,
	`namaibu` VARCHAR(100) NULL DEFAULT NULL,
	`namaayah` VARCHAR(100) NULL DEFAULT NULL,
	`pekerjaan` VARCHAR(100) NULL DEFAULT NULL,
	`agama` VARCHAR(100) NULL DEFAULT '0',
	`cetak` VARCHAR(100) NULL DEFAULT NULL,
	`alamat` VARCHAR(100) NULL DEFAULT NULL,
	`dokter` VARCHAR(100) NULL DEFAULT NULL,
	`tanggal` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COMMENT='tabel surat keterangan lahir'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=5
;
